
DROP TABLE IF EXISTS tb_belonging;
DROP TABLE IF EXISTS tb_game;
DROP TABLE IF EXISTS tb_game_list;


CREATE TABLE tb_game_list (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(100)
);

CREATE TABLE tb_game (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title VARCHAR(255),
  game_year INT,
  genre VARCHAR(50),
  platforms VARCHAR(255),
  score DOUBLE,
  img_url VARCHAR(255),
  short_description TEXT,
  long_description TEXT
);

CREATE TABLE tb_belonging (
  game_id BIGINT,
  list_id BIGINT,
  position INT,
  PRIMARY KEY (game_id, list_id)
);


INSERT INTO tb_game_list (name) VALUES ('Lista 1');

INSERT INTO tb_game (title, game_year, genre, platforms, score, img_url, short_description, long_description)
VALUES ('Game A', 2020, 'RPG', 'PC', 9.0, NULL, 'desc', 'long');

INSERT INTO tb_belonging (game_id, list_id, position) VALUES (1, 1, 0);

